<?php

namespace AppBundle\Repository;

/**
 * CommunauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunauteRepository extends \Doctrine\ORM\EntityRepository
{
}
