<?php

namespace AppBundle\Repository;

/**
 * CommunautesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunautesRepository extends \Doctrine\ORM\EntityRepository
{
}
