<?php

namespace AppBundle\Repository;

/**
 * CommunautesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class CommunautesRepository extends EntityRepository
{
    public function findAllValidTrue()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AppBundle:Communautes c WHERE c.validation='1'")
            ->getResult();
    }

    public function findAllValidFalse()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AppBundle:Communautes c WHERE c.validation='0'")
            ->getResult();
    }

    public function delete($id)
    {
        return $this->getEntityManager()
            ->createQuery("DELETE FROM AppBundle:Communautes c WHERE c.id=$id")
            ->getResult();
    }

    public function validate($id)
    {
        return $this->getEntityManager()
            ->createQuery("UPDATE AppBundle:Communautes c SET c.validation='1' WHERE c.id=$id")
            ->getResult();
    }

    public function modifier($id,$replace)
    {
        return $this->getEntityManager()
            ->createQuery("UPDATE AppBundle:Communautes c SET c.video='$replace' WHERE c.id=$id")
            ->getResult();
    }
}