<?php

namespace AppBundle\Repository;

/**
 * CommunautesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

