<?php
/**
 * Created by PhpStorm.
 * User: wilder
 * Date: 31/05/18
 * Time: 13:49
 */

namespace AppBundle\Repository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class CompteRepository extends EntityRepository
{
    public function modifier($id,$youtubeEmbed )
    {
        return $this->getEntityManager()
            ->createQuery("UPDATE AppBundle:Communautes c SET c.video='$youtubeEmbed ' WHERE c.id=$id")
            ->getResult();
    }
}