<?php
/**
 * Created by PhpStorm.
 * User: wilder
 * Date: 31/05/18
 * Time: 13:49
 */

namespace AppBundle\Repository;

/**
 * CompteRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class CompteRepository extends \Doctrine\ORM\EntityRepository
{

}