<?php

namespace AppBundle\Repository;

/**
 * EventImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventImageRepository extends \Doctrine\ORM\EntityRepository
{
}
