<?php

namespace AppBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function addVote($id)
    {
        return $this->getEntityManager()
            ->createQuery("UPDATE AppBundle:Participation p SET p.nbVote=p.nbVote + 1 WHERE p.id=$id")
            ->getResult();
    }
}
