<?php

namespace AppBundle\Repository;

/**
 * StartUpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StartUpsRepository extends \Doctrine\ORM\EntityRepository
{
}
