<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCompteById($id)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT u,c FROM AppBundle:User u JOIN u.communaute c where u.id = $id")
            ->getResult();


    }


}
