imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    images_directory: '%kernel.root_dir%/../web/uploads/img'
    app.path.images: /uploads/

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
            - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.images%'
            namer: vich_uploader.namer_uniqid

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                                              # since Symfony 3.4
        mailer: fos_user.mailer.twig_swift    # since Symfony 3.4
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

    registration:
        form:
            type: AppBundle\Form\RegistrationType

kms_froala_editor:

  # Froala license number if you want to use a purchased license.
  serialNumber: ""

  # Disable JQuery inclusion.
  includeJQuery: true

  # Disable CodeMirror inclusion.
  includeCodeMirror: false

   # Disable Font Awesome inclusion.
  includeFontAwesome: true

  # Disable all bundle javascripts inclusion (not concerning JQuery nor CodeMirror).
  # Usage: if you are using Grunt or other and you want to include yourself all scripts.
  includeJS: true

  # Disable all bundle CSS inclusion (not concerning Font Awesome nor CodeMirror).
  # Usage: if you are using Grunt or other and you want to include yourself all stylesheets.
  includeCSS: true

  # Change the froala base path.
  # Usage: let me know, I don't think it's usefull.
  # basePath: "/my/custom/path".

  # Custom JS file.
  # Usage: add custom plugins/buttons...
  # customJS: "/custom/js/path"